
  CREATE TABLE "SYSTEM"."CARONA_PETIENT_MINIPROJ" 
   (	"PID" NUMBER NOT NULL ENABLE, 
	"PNAME" VARCHAR2(40 BYTE), 
	"AGE" NUMBER, 
	"HOSPITALANME" VARCHAR2(40 BYTE), 
	"ADMIT_DATE" DATE, 
	"DISCHARGE_DATE" DATE, 
	"CITY" VARCHAR2(40 BYTE), 
	 CONSTRAINT "CARONA_PETIENT_MINIPROJ_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

