CREATE TABLE `ntspms615`.`carona_petient_miniproj` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `pname` VARCHAR(30) NULL,
  `AGE` INT NULL,
  `HOSPITALANME` VARCHAR(45) NULL,
  `ADMIT_DATE` DATE NULL,
  `DISCHARGE_DATE` DATE NULL,
  `CITY` VARCHAR(45) NULL,
  PRIMARY KEY (`pid`));
